Map<String, String> mapCountryToIso = {
  'USA': 'US',
  'Spain': 'ES',
  'Italy': 'IT',
  'France': 'FR',
  'Germany': 'DE',
  'UK': 'GB',
  'Turkey': 'TR',
  'Iran': 'IR',
  'Russia': 'RU',
  'Belgium': 'BE',
  'Brazil': 'BR',
  'Canada': 'CA',
  'Netherlands': 'NL',
  'Switzerland': 'CH',
  'Portugal': 'PT',
  'India': 'IN',
  'Peru': 'PE',
  'Ireland': 'IE',
  'Sweden': 'SE',
  'Austria': 'AT',
  'Israel': 'IL',
  'Saudi Arabia': 'SA',
  'Japan': 'JP',
  'S. Korea': 'KR',
  'Chile': 'CL',
  'Ecuador': 'EC',
  'Poland': 'PL',
  'Romania': 'RO',
  'Pakistan': 'PK',
  'Singapore': 'SG',
  'Mexico': 'MX',
  'UAE': 'AE',
  'Denmark': 'DK',
  'Norway': 'NO',
  'Indonesia': 'ID',
  'Czechia': 'CZ',
  'Serbia': 'RS',
  'Australia': 'AU',
  'Philippines': 'PH',
  'Qatar': 'QA',
  'Belarus': 'BY',
  'Ukraine': 'UA',
  'Malaysia': 'MY',
  'Dominican Republic': 'DO',
  'Panama': 'PA',
  'Finland': 'FI',
  'Colombia': 'CO',
  'Luxembourg': 'LU',
  'Bangladesh': 'BD',
  'Egypt': 'EG',
  'South Africa': 'ZA',
  'Morocco': 'MA',
  'Argentina': 'AR',
  'Thailand': 'TH',
  'Algeria': 'DZ',
  'Moldova': 'MD',
  'Greece': 'GR',
  'Hungary': 'HU',
  'Kuwait': 'KW',
  'Kazakhstan': 'KZ',
  'Bahrain': 'BH',
  'Croatia': 'HR',
  'Iceland': 'IS',
  'Uzbekistan': 'UZ',
  'Iraq': 'IQ',
  'Estonia': 'EE',
  'Oman': 'OM',
  'Azerbaijan': 'AZ',
  'New Zealand': 'NZ',
  'Armenia': 'AM',
  'Lithuania': 'LT',
  'Slovenia': 'SI',
  'Bosnia and Herzegovina': 'BA',
  'North Macedonia': 'MK',
  'Slovakia': 'SK',
  'Cameroon': 'CM',
  'Afghanistan': 'AF',
  'Cuba': 'CU',
  'Ghana': 'GH',
  'Hong Kong': 'HK',
  'Bulgaria': 'BG',
  'Tunisia': 'TN',
  'Ivory Coast': 'CI',
  'Djibouti': 'DJ',
  'Cyprus': 'CY',
  'Latvia': 'LV',
  'Andorra': 'AD',
  'Diamond Princess': '',
  'Guinea': 'GN',
  'Lebanon': 'LB',
  'Nigeria': 'NG',
  'Costa Rica': 'CR',
  'Niger': 'NE',
  'Albania': 'AL',
  'Bolivia': 'BO',
  'Kyrgyzstan': 'KG',
  'Burkina Faso': 'BF',
  'Uruguay': 'UY',
  'Honduras': 'HN',
  'Channel Islands': 'GB',
  'San Marino': 'SM',
  'Palestine': 'PS',
  'Malta': 'MT',
  'Jordan': 'JO',
  'Taiwan': 'TW',
  'Senegal': 'SN',
  'Réunion': 'RE',
  'Georgia': 'GE',
  'DRC': 'CD',
  'Mauritius': 'MU',
  'Montenegro': 'ME',
  'Sri Lanka': 'LK',
  'Isle of Man': 'IM',
  'Kenya': 'KE',
  'Guatemala': 'GT',
  'Venezuela': 'VE',
  'Mayotte': 'YT',
  'Vietnam': 'VN',
  'Mali': 'ML',
  'Tanzania': 'TZ',
  'Somalia': 'SO',
  'El Salvador': 'SV',
  'Jamaica': 'JM',
  'Paraguay': 'PY',
  'Faeroe Islands': 'FO',
  'Martinique': 'MQ',
  'Congo': 'CG',
  'Guadeloupe': 'GP',
  'Rwanda': 'RW',
  'Brunei': 'BN',
  'Gibraltar': 'GI',
  'Cambodia': 'KH',
  'Madagascar': 'MG',
  'Gabon': 'GA',
  'Myanmar': 'MM',
  'Trinidad and Tobago': 'TT',
  'Ethiopia': 'ET',
  'Sudan': 'SD',
  'Liberia': 'LR',
  'Aruba': 'AW',
  'French Guiana': 'GF',
  'Monaco': 'MC',
  'Bermuda': 'BM',
  'Togo': 'TG',
  'Maldives': 'MV',
  'Liechtenstein': 'LI',
  'Equatorial Guinea': 'GQ',
  'Barbados': 'BB',
  'Zambia': 'ZM',
  'Sint Maarten': 'SX',
  'Cabo Verde': 'CV',
  'Guyana': 'GY',
  'Cayman Islands': 'KY',
  'Bahamas': 'BS',
  'Uganda': 'UG',
  'Haiti': 'HT',
  'French Polynesia': 'PF',
  'Benin': 'BJ',
  'Libya': 'LY',
  'Guinea-Bissau': 'GW',
  'Sierra Leone': 'SL',
  'Macao': 'MO',
  'Nepal': 'NP',
  'Syria': 'SY',
  'Eritrea': 'ER',
  'Mozambique': 'MZ',
  'Saint Martin': 'MF',
  'Mongolia': 'MN',
  'Chad': 'TD',
  'Zimbabwe': 'ZW',
  'Angola': 'AO',
  'Eswatini': 'SZ',
  'Antigua and Barbuda': 'AG',
  'Timor-Leste': 'TL',
  'Botswana': 'BW',
  'Laos': 'LA',
  'Belize': 'BZ',
  'Malawi': 'MW',
  'Fiji': 'FJ',
  'New Caledonia': 'NC',
  'Dominica': 'DM',
  'Namibia': 'NA',
  'Saint Kitts and Nevis': 'KN',
  'Saint Lucia': 'LC',
  'Curaçao': 'CW',
  'CAR': 'CF',
  'Grenada': 'GD',
  'St. Vincent Grenadines': 'VC',
  'Turks and Caicos': 'TC',
  'Falkland Islands': 'FK',
  'Greenland': 'GL',
  'Montserrat': 'MS',
  'Seychelles': 'SC',
  'Nicaragua': 'NI',
  'Gambia': 'GM',
  'Suriname': 'SR',
  'MS Zaandam': '',
  'Vatican City': '',
  'Mauritania': 'MR',
  'Papua New Guinea': 'PG',
  'Bhutan': 'BT',
  'St. Barth': 'BL',
  'Western Sahara': 'EH',
  'British Virgin Islands': 'VG',
  'Burundi': 'BI',
  'Caribbean Netherlands': 'BQ',
  'Sao Tome and Principe': 'ST',
  'South Sudan': 'SS',
  'Anguilla': 'AI',
  'Saint Pierre Miquelon': 'PM',
  'Yemen': 'YE',
  'China': 'CN',
  'Diamond Princess': 'XX',
  'MS Zaandam': 'XX',
  'Vatican City': 'VA',
};
